/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sschakraborty.poc.crypto;

import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        assertTrue(true);
    }
}
